### ISSUE TITLE
Error "regeneratorRuntime is not defined" while using async / await

### ISSUE THREAD

**Issue by SacDin** [express-vue/vue-pronto#103]
### Description of Issue
Rendering components dynamically by providing data. It is simple component with one method havign async / await.

### Stack Trace / Console Log
```
ReferenceError: regeneratorRuntime is not defined
    at /project/views/plugins.vue:24:36
    at /project/views/plugins.vue:56:6
    at Object.<anonymous> (/project/views/plugins.vue:59:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at requireFromString (/project/node_modules/require-from-string/index.js:28:4)
    at FindAndReplaceComponents.then.compiled (/project/node_modules/vue-pronto/lib/renderer/renderer.js:398:36)
```

### Additional Comments
It seems like async / await is not yet supported. Is there any way to use async / await with vue-pronto ?

**Comment by danielcherubini** [comment]
can you please try this again with the new webpack-renderer

https://github.com/express-vue/express-vue#migration-to-webpack-renderer
